homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include_dir_merge_named customize

# Show links to resources in log and frontend
#introduction:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_server

  ssh_server:
    title: SSH Server
    icon: mdi:wrench
    url: !secret ssh_server

media_player:
  - platform: xboxone
    device: !secret xbox_one
    name: Weird Room Xbox One
# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Update custom components
custom_updater:
  show_installable: false
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    # Mini graph lovelace card
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
# Discover some devices automatically
discovery:

#http:
#  base_url: !secret server_base_url
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.86.0/24
    track_new_devices: yes

#  - platform: owntracks
#    max_gps_accuracy: 200
#    mqtt_topic: "owntracks/#"

  - platform: google_maps
    username: !secret google_maps_username
    password: !secret google_maps_password

#mqtt:
#  broker: !secret MQTT_server
#  port: 16312
#  username: !secret MQTT_username
#  password: !secret MQTT_password

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

notify:
  - platform: webostv
    host: 192.168.86.192
    name: weirdroom_tv

  - name: telegram
    platform: telegram
    api_key: !secret telegram_api
    chat_id: !secret telegram_chatID

telegram_bot:
  platform: polling
  api_key: !secret telegram_api
  allowed_chat_ids:
    - !secret telegram_chatID

sensor: !include_dir_merge_list sensor

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

camera:
  - name: livingroom_camera
    platform: generic
    still_image_url: !secret living_room_camera

  #Boys Room Monitor
  - platform: mjpeg
    name: kids_room_camera
    mjpeg_url: !secret boysRoomCameraVideo
    still_image_url: !secret boysRoomCameraStill

switch: !include_dir_merge_list switch
group: !include_dir_merge_named group
automation: !include_dir_merge_list automation
script: !include scripts.yaml
input_select: !include input_select.yaml
#packages: !include_dir_named packages
# Enables the frontend
frontend: !include frontend.yaml
