- platform: darksky
  api_key: !secret forecast_key
#  forecast:
#    - 1
#    - 2
#    - 3
#    - 4
#    - 5
  monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - temperature_high
      - temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
  update_interval:
    minutes: 5
#THESE ARE THE ORIGINAL MONITORED CONDITIONS
#    - summary
#    - precip_intensity
#    - precip_intensity_max
#    - temperature
#    - wind_speed
#    - cloud_cover
#    - humidity
#    - minutely_summary
#    - uv_index
