- alias: 'Telebot start'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/start'
  action:
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: "Hello, I am the Ramsey House Bot! The custom keyboard is activated."
        keyboard:
          - '/ping, /start, /guestMode'
          - '/weather'

- alias: 'Telebot Ping'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/ping'
  action:
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: "Hello, you sent ping... I send pong... I'm here dammit!"

- alias: 'Telebot GuestMode'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/guestMode'
  action:
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: "Guest mode has been set"

- alias: 'Telebot Weather'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/weather'
  action:
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: "The weather is {{ states('sensor.dark_sky_minutely_summary') }}"

- alias: 'Telebot Turn Lights On'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/lightsOn'
  action:
    - service: homeassistant.turn_on
      entity_id: group.all_lights
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: "Turned all of the lights on!"

- alias: 'Telebot Turn Lights Off'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/lightsOff'
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_lights
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: "Turned all of the lights off!"

- alias: 'Telebot How Many Lights On'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/lightsOn'
  action:
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: "There are {{ states.light|selectattr('state', 'equalto', 'on')|list|length }} light(s) on"
